name: Build and Deploy Azure Functions

on:
  push:
    paths:
      - 'CryptoFunctionApp/**'  # Adjust the folder path as needed
  pull_request:
    paths:
      - 'CryptoFunctionApp/**'  # Adjust the folder path as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Publish the project
        run: dotnet publish --configuration Release --no-build --output ./publish

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: 'cryptofunc-e0x2gf'
          package: './publish'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
