name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'CryptoPortfolioInfrastructure/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'CryptoPortfolioInfrastructure/**'
      - '.github/workflows/main.yml'

jobs:
  terraform:
    name: Terraform
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./CryptoPortfolioInfrastructure

      - name: Terraform Apply
        if: github.event_name == 'push'
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./CryptoPortfolioInfrastructure

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan
        working-directory: ./CryptoPortfolioInfrastructure

      - name: Terraform Destroy
        if: github.event_name == 'delete'
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ./CryptoPortfolioInfrastructure
